### ISSUE TITLE
Replace assert statement

### ISSUE THREAD

**Issue by wwwjfy** [python-gino/gino#258]
`assert` is preferred not to be used in production code because it's no effect when optimization mode is on (executed with parameter `-O`).

**Comment by fantix** [comment]
Yeah, we shall check each usage to see if they should use something else, refs https://wiki.python.org/moin/UsingAssertionsEffectively

**Comment by wwwjfy** [comment]
Since `-O` only removes `assert` statements and `__debug__`, I don't know how many are using it in real life. Consider it a corner case.
