### ISSUE TITLE
[RFC] Move extensions to examples

### ISSUE THREAD

**Issue by wwwjfy** [python-gino/gino#571]
There have been some issues before about extensions of web framework. Most of them are caused by backward incompatible. Here comes the latest one #569.

It's unreasonable to have compatibility code to be adaptable to different versions of a given framework. Because when the users import it, the version is definite.

And for users need later version of Gino and earlier version of Sanic for example, or the opposite way, it's currently impossible.

I can think of 2 options:
1) Another package (can be in the same repo though) to contain extensions.
2) Putting the extensions in example (or something else) folder. Users can copy and make changes accordingly, and maybe they can also create PR to make it up to date.

Personally I prefer 2, and we can reduce maintenance cost from our side, so I don't need to know how to use each one and follow up all the updates.

**Comment by wwwjfy** [comment]
@fantix thoughts?

**Comment by fantix** [comment]
@wwwjfy sorry for the late reply! Yeah I agree that we should go for 2.

**Comment by fantix** [comment]
Sorry I changed my mind - maybe we should go for `1`. Because in `2` the examples are anyway maintained, but in `1` the extension packages **can be** outdated without affecting the main repo.

I've created https://github.com/python-gino/ to be the "GINO community", removed extensions, switched to [Poetry](https://python-poetry.org/) and re-organizing documentation. When ready, I'll move this repo to https://github.com/python-gino/gino. Please kindly advise!

**Comment by fantix** [comment]
I think we could make `gino.ext` a [namespace](https://packaging.python.org/guides/packaging-namespace-packages/#pkg-resources-style-namespace-packages) to be backward-compatible.

**Comment by wwwjfy** [comment]
Sure. Only difference I think is the maintenance cost, i.e. `gino versions` * `framework versions`

**Comment by fantix** [comment]
Removed all extensions in e77b19eb4ae0d28ed47c5c21ed7c0e50ee20d5e8.

**Comment by fantix** [comment]
All 5 existing extensions are now sub-projects: https://github.com/python-gino?q=extension&type=&language=

I can at least maintain the gino-starlette extension as it is used in production in my work for now. The remaining are marked as unmaintained until adopted.
