### ISSUE TITLE
can't query data under Sanic service

### ISSUE THREAD

**Issue by sunshineinwater** [python-gino/gino#626]
Sorry for disturb again.

### Description

- situation:
It works well in clean environment . But It have problem under Sanic service.

- error information:

asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

### Full Code demo

```python
from gino import Gino
from sanic import response, Sanic
from asyncio import get_event_loop

'''
#
#   Gino
#
'''
url = "postgresql://postgres:postgres@localhost:5432/postgresql"
db = Gino()
get_event_loop().run_until_complete(db.set_bind(bind=url))


# define Model
class userTable(db.Model):
    # 
    __tablename__ = 'userTable'
    #
    id = db.Column(db.Integer, primary_key=True)
    account_id = db.Column(db.String(40), unique=True, index=True)
    phone = db.Column(db.String(20))
    password_hash = db.Column(db.String(128))


# test Query data
data = get_event_loop().run_until_complete(userTable.get(9))
print(data.account_id)  # It works well

'''
#
#   sanic + gino
#
'''

app = Sanic(name=__name__)


@app.route("/", methods=["GET"])
async def test(request):
    data = await userTable.get(9)
    print(data)
    return response.text("ok")


if __name__ == '__main__':
    app.run(debug=True, port=80, host='0.0.0.0', workers=1)
```

**Comment by fantix** [comment]
Could you please share the versions of your Python, GINO and aiocontextvars?

**Comment by sunshineinwater** [comment]
yes, they are:
- GINO version:0.8.5
- Python version:3.7
- asyncpg version:0.20.0
- aiocontextvars version:0.2.2

**Comment by sunshineinwater** [comment]
谢谢，搞定了，没有引用from gino.ext.sanic import Gino导致的。从文档的小角落里发现了这条....

THX for reply.  It figure out by using method of "from gino.ext.sanic import Gino", it can be find in Gino document.

**Comment by fantix** [comment]
好的，不客气，我也没注意到那一句 `import`。。。

However, the root cause why your previous code doesn't work was reported here: MagicStack/asyncpg#56, and it is because of the way Sanic tweaks event loops for its worker subprocesses. **Simply having the connection pool/engine initialization in Sanic `before_server_start` will solve the problem.**
