### ISSUE TITLE
Transaction questions

### ISSUE THREAD

**Issue by xmrdsc** [python-gino/gino#633]
First question is; does Gino's CRUD operations work within transactions?

Say I have this:

```python3
import asyncio
from gino import Gino

db = Gino()

class Test(db.Model):
    __tablename__ = 'test'
    id = db.Column(db.String, primary_key=True)


async def test():
    await db.set_bind('postgresql://test:test@localhost:5432/gino')
    foo = await Test.create(id='before')
    async with db.transaction():
        status = await (
            foo.update
            .where(Test.id == "before")
            .values(id="after")
            .gino.status()
        )

if __name__ == '__main__':
    asyncio.ensure_future(test())
    asyncio.get_event_loop().run_until_complete(test())
```

I read [somewhere else](https://github.com/python-gino/gino/issues/228#issuecomment-391581219) on this issue tracker that `apply()` needs to be given a `bind=tx.connection` parameter, [even though in the testing suite](https://github.com/python-gino/gino/blob/ef1d9826f29540ef4a2756dfa05d046386a96689/tests/test_transaction.py#L27) it does not use this parameter.

Should I be using `apply()` on my `.update()` queries? If so, should I pass it the connection?

Thanks in advance.

**Comment by fantix** [comment]
> First question is; does Gino's CRUD operations work within transactions?

Yes, all GINO executions (including CRUD operations) reuse connection from the context (usually the same `asyncio.Task`) if `bind` is not specifically set. `aiocontextvars` is a default dependency now (0.8.x) and will be built-in after 1.0, so the contextual connection feature should always be available, in most cases you don't have to provide the `bind` parameter (you'll know if you need it).

> Should I be using `apply()` on my `.update()` queries? If so, should I pass it the connection?

There're to types of `update` - one is per-instance update:

```python
user = await User.get(user_id)
await user.update(name="new").apply()
```

The other is batch-update - this is simply the [SQLAlchemy core update](https://docs.sqlalchemy.org/en/13/core/dml.html#sqlalchemy.sql.expression.update) statement:

```python
await User.update.where(User.created < expiry).values(enabled=False).gino.status()
```

In your code, it is the batch-update, so no `apply()`.

**Comment by xmrdsc** [comment]
Oh, I see. Thank you for the quick reply!
