### ISSUE TITLE
sssssssssssssssssssssssssss

### ISSUE THREAD

**Issue by reinoldus** [python-gino/gino#648]
* GINO version:
* Python version:
* asyncpg version:
* aiocontextvars version:
* PostgreSQL version:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by reinoldus** [comment]
cat walked on laptop and opened this issue. Sorry! I think I can't delete it

**Comment by fantix** [comment]
![image](https://user-images.githubusercontent.com/1751601/78503314-7ba60b80-772b-11ea-81bb-5adecc194d29.png)
