### ISSUE TITLE
Do you have any plans to support SQL Server

### ISSUE THREAD

**Issue by xiaohuazi123** [python-gino/gino#666]
* GINO version:
* Python version:
* asyncpg version:
* aiocontextvars version:
* PostgreSQL version:

### Description

Do you have any plans to support SQL Server  
Because our production environment database is Microsoft SQL Server, and we are now using sqlalchemy to develop database applications.
Thanks.
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by wwwjfy** [comment]
Close as it's duplicated with #527

**Comment by xiaohuazi123** [comment]
Thanks.
