### ISSUE TITLE
[question] Tornado fork mode with Gino

### ISSUE THREAD

**Issue by flapili** [python-gino/gino#668]
Hi, I am trying to create a REST API template based on Tornado and Gino and I would  like your opinion/expertise on the fork mode.

is that likely to pose any problem?
when should I fork ? after import models ? before the set_bind ? no matter ?
what could be the side effect on the event loop ?

**Comment by fantix** [comment]
I assume you are talking about [this Tornado feature](https://www.tornadoweb.org/en/stable/guide/running.html#processes-and-ports). Creating database pools / engines cleanly in sub-processes is definitely a safer choice. I'm wondering if @ppsirg had any experience to share for this scenario?

**Comment by flapili** [comment]
Ok, thanks for the advice,
after a lot of thinking, i finally came to the conclusion that this does not concern my framework project to manage the fork process and this question belongs to the end user.
