### ISSUE TITLE
UniqueConstraint not added to table with alembic migration

### ISSUE THREAD

**Issue by makupi** [python-gino/gino#669]
* GINO version: 1.0.0
* Python version: 3.8.2
* asyncpg version: 0.20.1
* aiocontextvars version: 0.2.2
* PostgreSQL version: 12.2

### Description

I tried to add a UniqueConstraint to my Model, when trying to migrate the database with alembic the UniqueConstraint was **not** added to postgreSQL.

### What I Did

```python
class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.BIGINT)
    guild_id = db.Column(db.BIGINT)
    birthday = db.Column(db.Date)

    db.UniqueConstraint("user_id", "guild_id", name="guild_user")
```

```
added UniqueConstraint to model
alembic revision --autogenerate
alembic upgrade head
```

After that I checked pgAdmin table properties > constraints > unique and it was empty.

**Comment by fantix** [comment]
Could you please try assigning the constraint to an attribute? Like this:

```python
class User(db.Model):
    _guild_user_uniq = db.UniqueConstraint("user_id", "guild_id", name="guild_user")
```

The attribute name `_guild_user_uniq` is not used by GINO but it plays an important role to pass its value to the model initializer.

**Comment by makupi** [comment]
Yes that works! Thank you very much!
