### ISSUE TITLE
Load balancer with Gino's create_engine

### ISSUE THREAD

**Issue by ThanVij29** [python-gino/gino#670]
Hello,

* GINO version: 1.0.0
* Gino-Starlette version: 0.1.1
* FastAPI version: 0.54.1
* Python version: 3.8.1
* asyncpg version: 0.20.1
* PostgreSQL version: PostgreSQL 12.1 

### Description

I want to use two different engines, depending on the Request method. If the request method is Get, it will use the engine which is connected with read only and for Put/Post/Patch/Delete, it will use the engine which is connected with admin user. My intention is to have a load balancer. I tried Fantix's suggestion here: https://github.com/python-gino/gino/issues/209#issuecomment-614862013.
But, once the first request is Get, we are not able to write anything for other Put/Post/Patch/Delete Request.

### What I Did
I tried different methods while using Fantix’s suggestion:
**1) First one with Gino’s create_engine and acquire:**

I initialized two engines on app startup:
```
 engine_adm = await create_engine(DATABASE_URL, max_size=1, min_size=1)
 engine_ro = await create_engine(DATABASE_URL_RO, max_size=1, min_size=1)
```

Then edited the set_db_mode:

```
@app.middleware("http")
async def set_db_mode(request: Request, call_next):
    global e,engine_adm,engine_ro
    engine = None
    e = Future()
    if request.method != 'GET':
        engine = await engine_adm.acquire()
    else:
        engine = await engine_ro.acquire()
    if e:    
        e.set_result(engine)
    try:
        await e
    finally:
        current_connection = await engine.release()
        e = current_connection
    return await call_next(request)
```

I tested the api with Jmeter with the following configuration:
Runned for : 20 min, Number of Threads (User) : 300, Ramp-up period (seconds) : 600

I got this result:

<img width="1141" alt="Capture d’écran 2020-05-11 à 14 16 24" src="https://user-images.githubusercontent.com/65223950/81670198-8f8a0f00-9447-11ea-85b3-3f0c0b5ed08b.png">

**2) Then I tried with SQLAlchemy’s create_engine and connect (which is still used with Gino’s db instance):**

I initialized two engines on app startup:
```
engine_adm =  create_engine(DATABASE_URL,pool_size=1,max_overflow=0,poolclass=QueuePool)
engine_ro =  create_engine(DATABASE_URL_RO,pool_size=1,max_overflow=0,poolclass=QueuePool)
```

Then I edited the set_db_mode:

```
@app.middleware("http")
async def set_db_mode(request: Request, call_next):
    global e,engine_adm,engine_ro
    engine = None
    if e is None:
        e = Future()
        if request.method != 'GET':
            engine =  engine_adm.connect()
        else:
            engine =  engine_ro.connect()
        e.set_result(engine)
    try:
        await e
    finally:
        current_connection = engine.close() if engine else None
        e = current_connection
    return await call_next(request)
```
I tested the api with Jmeter exactly with the same configuration:

<img width="1028" alt="Capture d’écran 2020-05-12 à 09 13 46" src="https://user-images.githubusercontent.com/65223950/81670554-15a65580-9448-11ea-9e41-1575bac43b03.png">

As we can see there is a huge difference. 

Have you got any suggestion to improve with Gino's create_engine?
If not, do you think its ok to use SQLAlchemy’s create_engine? And will it have any impact on the asynchronism?
Or is there any other way to do?

**Comment by fantix** [comment]
Thanks for sharing your benchmark and questions!

> ```python
> @app.middleware("http")
> async def set_db_mode(request: Request, call_next):
>     global e,engine_adm,engine_ro
>     engine = None
>     e = Future()
>     if request.method != 'GET':
>         engine = await engine_adm.acquire()
>     else:
>         engine = await engine_ro.acquire()
>     if e:    
>         e.set_result(engine)
>     try:
>         await e
>     finally:
>         current_connection = await engine.release()
>         e = current_connection
>     return await call_next(request)
> ```

This doesn't look quite right to me - I'm actually confused about how this code worked for you. The `Future()` was supposed to be used as a lazy-initialization pattern. Please refer to [this example](https://python-gino.org/docs/en/master/how-to/faq.html#how-to-use-multiple-databases-for-different-users-on-the-fly) for a more complete setup of multiple engines.

Regarding overall GINO performance, please follow #631 for updates.

From your benchmarks, the P90 latency for **async** is `56ms` and `118ms`, while the P90 latency for **blocking** SQLAlchemy is `3,394ms` and `3,413ms`. And the max latency in **async** is even something like `14` minutes. I think there must be something seriously wrong here - in both server setups.

> do you think its ok to use SQLAlchemy’s create_engine? And will it have any impact on the asynchronism?

Calling blocking methods in the main thread is an absolute NO, please see also [the why](https://python-gino.org/docs/en/master/explanation/why.html#how-to-access-database).

**Comment by ThanVij29** [comment]
Thanks for your answers.

I understand what you mean but Infact this code worked for me. I will try your suggestion [in your example](https://python-gino.org/docs/en/master/how-to/faq.html#how-to-use-multiple-databases-for-different-users-on-the-fly) and update my results.

**Comment by ThanVij29** [comment]
Hello Fantix,

Im sorry for the late reply.
I was able to test your solution and the results are much better. Thank you.

Here is a benchmark for the same requests with max_size and min_size to 1, in create_engine: 
<img width="1139" alt="Capture d’écran 2020-06-11 à 14 04 41" src="https://user-images.githubusercontent.com/65223950/84383552-c42aeb00-abec-11ea-9e4e-2e3f840c3f84.png">
