### ISSUE TITLE
Is singular naming convention allowed for `__tablename__`?

### ISSUE THREAD

**Issue by danieljfarrell** [python-gino/gino#671]
### Description

I'm trying to implement models with GINO and I came across the comment in the [documentation](https://python-gino.org/docs/en/master/tutorials/tutorial.html)

> Note that the fixed __tablename__ property is required. GINO suggests singular for model names, and plural for table names. 

I am wondering why GINO suggests using this convention? Is it possible to use another convention without any side effects?

**Comment by fantix** [comment]
Oh sure - I think this is just a general ORM suggestion, and it is very personal. I don't think there're any side effects to use a different approach, as far as any of such code makes sense to you:

```python
current_user = Users()
```

```python
current_user = User()
```

```sql
SELECT name FROM user WHERE user.id = 123;
```

```sql
SELECT name FROM users WHERE users.id = 123;
```

(people are suggesting this too:
```sql
SELECT name FROM users user WHERE user.id = 123;
```
)

**Comment by danieljfarrell** [comment]
Thanks @fantix! Using GINO in production app where this seems to be the convention.
