### ISSUE TITLE
password type

### ISSUE THREAD

**Issue by flapili** [python-gino/gino#677]
Hi,

to hash a password in a database collumn what would you recommand ?
does [sqlalchemy_utils.types.password](https://sqlalchemy-utils.readthedocs.io/en/latest/_modules/sqlalchemy_utils/types/password.html) is fine ?
should I hash by myself ?

```
class MyTable(db.Model):
    _pwd = db.Column("pwd", db.String)

    @property
    def pwd(self):
        return _pwd

    @pwd.setter
    def pwd(self, val):
        self._pwd = some_hash_fonction(_pwd)
```
?

**Comment by fantix** [comment]
Yeah, `pbkdf2_sha512` might be okay - but you're also open to scrypt or argon2, please kindly read more here: https://medium.com/analytics-vidhya/password-hashing-pbkdf2-scrypt-bcrypt-and-argon2-e25aaf41598e
