### ISSUE TITLE
What Column Types Are Available?

### ISSUE THREAD

**Issue by austincollinpena** [python-gino/gino#684]
For example I see [here](https://github.com/python-gino/gino/issues/160) talks about enum, and [on this issue](https://github.com/python-gino/gino/issues/287) I see a Datetime() field.

Is it all of the columns from [SQLAlchemy's core](https://docs.sqlalchemy.org/en/13/core/type_basics.html)? 

If so, when do I call the column like db.String vs db.DateTime()?

Some clarification here or in the docs would be appreciated

**Comment by fantix** [comment]
> Is it all of the columns from SQLAlchemy's core?

Yes, GINO is a wrapper of SQLAlchemy Core.

`db.*` is just a shortcut for `sqlalchemy.*`:

https://github.com/python-gino/gino/blob/f5108222c30767210a3d74d0740f39313093c5a0/src/gino/api.py#L367-L370

**Comment by austincollinpena** [comment]
Thank you for the help!
