### ISSUE TITLE
Continually Getting TypeError: 'GinoExecutor' object is not callable

### ISSUE THREAD

**Issue by austincollinpena** [python-gino/gino#692]
* GINO version: 1.0.0
* Python version: 3.7 
* asyncpg version: 0.20.1
* aiocontextvars version: Not installed
* PostgreSQL version: 12.1

### Description

Attempting to make a simple query but am unable to. 

### What I Did

While running:
```
domain = await Domain.get(Domain.domain == 'http://domain.com').gino().first()
```
I get:
```
TypeError: 'GinoExecutor' object is not callable
```
In context, here's some more code:

```python
./db/__init__.py
from gino import Gino
from scraper import config

print(config.DB_DSN)

import asyncio

gino_db = Gino()

async def main():
    await gino_db.set_bind(config.DB_DSN)

asyncio.get_event_loop().run_until_complete(main())

# Import your models here so Alembic will pick them up
from db.models import *
```

My main.py:

```python
...
    loop.run_until_complete(init_db())
...
```

And finally the init_db() function
```python
async def init_db():
    engine = await gino_db.set_bind(config.DB_DSN, echo=True)
    domain = await Domain.query.where(Domain.domain == 'http://equipomedia.com').gino().first()
```

What's going wrong? In the same code I'm able to call ```domains = await Domain.query.gino.all()``` and get a valid response.

[Github Repo](https://github.com/austincollinpena/spell-check-scraper)

**Comment by aragentum** [comment]
```
domain = await Domain.query.where(Domain.domain == 'http://equipomedia.com').gino().first()
```

`gino` is not a function you should try something like this:
```
domain = await Domain.query.where(Domain.domain == 'http://equipomedia.com').gino.first()
```
-----------------------
About your project, you forget `.gino.first()` in
https://github.com/austincollinpena/spell-check-scraper/blob/600ccd2f29e1ec1ff6422435bbd359bf9f0d73ef/scraper/utils/data/gino_utils.py:
```
domain = await Domain.query.where(Domain.domain == 'http://equipomedia.com')
```

**Comment by austincollinpena** [comment]
@aragentum 

You're telling me to query like this:

```
domain = await Domain.query.where(Domain.domain == 'http://equipomedia.com').gino.first()
```
But isn't that what I'm already querying? Your two sample look the same to me.

And I'll get back to you on the suggestion for the different way to run the program, thanks for it! I'm still trying to wrap my head around async programming!

**Comment by aragentum** [comment]
@austincollinpena 
pay attention on the end of this line - in your code `.gino().first()` in my code `.gino.first()`

**Comment by austincollinpena** [comment]
Can't believe I missed that! Thanks Aragentum.

Can I buy you a coffee? Donate to Gino somehow? I'm trying to find gaps in the docs where I can contribute at the moment as a way of giving back (simple places ;)

Thanks for the tip on cleaning up my async functions too!
