### ISSUE TITLE
什么时候可以支持mssql

### ISSUE THREAD

**Issue by jhhuang2000** [python-gino/gino#708]
* GINO version:
* Python version:
* asyncpg version:
* aiocontextvars version:
* PostgreSQL version:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by jhhuang2000** [comment]
什么时候可以支持mssql?
同类型的异步orm框架, 都没有支援mssql的, 如果GINO能优先支持,那就很赞了

**Comment by wwwjfy** [comment]
Duplicate of #527 

我们没有 mssql 的使用场景，所以目前没有计划。欢迎提交 PR
