### ISSUE TITLE
How to close print sql

### ISSUE THREAD

**Issue by oleeks** [python-gino/gino#710]
adding `echo` does not work, how can I close it?
```
db = Gino(
    dsn=db_dsn,
    pool_min_size=config.DB_POOL_MIN_SIZE,
    pool_max_size=config.DB_POOL_MAX_SIZE,
    echo=`config.DB_ECHO`,
    ssl=config.DB_SSL,
    use_connection_for_request=config.DB_USE_CONNECTION_FOR_REQUEST,
    retry_limit=config.DB_RETRY_LIMIT,
    retry_interval=config.DB_RETRY_INTERVAL,
)
```

**Comment by ferstar** [comment]
I met the same problem too, and here is my solution:

1. keep the `echo=False` param
2. set log level of `gino.engine._SAEngine` to `logging.ERROR` or other
```python
import logging
logging.basicConfig()
logging.getLogger('gino.engine._SAEngine').setLevel(logging.ERROR)  # Turn off the annoying gino SQL echo message
```

BTW, this problem may cause by the codes below:
https://github.com/sqlalchemy/sqlalchemy/blob/67e8359931b18d2d13231a0d4e665b03958d6d7f/lib/sqlalchemy/engine/base.py#L98
Obviously the `echo` param doesn't work at all @fantix

**Comment by guifa2015** [comment]
> I met the same problem too, and here is my solution:
> 
> 1. keep the `echo=False` param
> 2. set log level of `gino.engine._SAEngine` to `logging.ERROR` or other
> 
> ```python
> import logging
> logging.basicConfig()
> logging.getLogger('gino.engine._SAEngine').setLevel(logging.ERROR)  # Turn off the annoying gino SQL echo message
> ```
> 
> BTW, this problem may cause by the codes below:
> https://github.com/sqlalchemy/sqlalchemy/blob/67e8359931b18d2d13231a0d4e665b03958d6d7f/lib/sqlalchemy/engine/base.py#L98
> Obviously the `echo` param doesn't work at all @fantix

Thanks

**Comment by fantix** [comment]
I'm sorry - this does seem to be an issue. I'll fix it in GINO 1.0.x, and GINO 1.4.x won't have this issue any more: #679.

**Comment by ferstar** [comment]
Glad to hear that:-)

**Comment by ggwmwgg** [comment]
> > I met the same problem too, and here is my solution:
> > 
> > 1. keep the `echo=False` param
> > 2. set log level of `gino.engine._SAEngine` to `logging.ERROR` or other
> > 
> > ```python
> > import logging
> > logging.basicConfig()
> > logging.getLogger('gino.engine._SAEngine').setLevel(logging.ERROR)  # Turn off the annoying gino SQL echo message
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > BTW, this problem may cause by the codes below:
> > https://github.com/sqlalchemy/sqlalchemy/blob/67e8359931b18d2d13231a0d4e665b03958d6d7f/lib/sqlalchemy/engine/base.py#L98
> > Obviously the `echo` param doesn't work at all @fantix
> 
> Thanks

Thanks x2 =)
