### ISSUE TITLE
[Q] How to create or update?

### ISSUE THREAD

**Issue by wildprint** [python-gino/gino#711]
* GINO version: 1.0.1
* Python version: 3.8.3
* asyncpg version: 0.20.1
* aiocontextvars version:
* PostgreSQL version: 12

### Description
    class Account(db.Model):
        __tablename__ = "accounts"

       id = db.Column(db.Integer(), primary_key=True)
       phone = db.Column(db.String(), unique=True)
       password = db.Column(db.String())

There's my model. Phone field is unique. When I create (`Account.create(...)`) new account (phone isn't duplicated) it's ok but when number I got `asyncpg.exceptions.UniqueViolationError`
I can check phone exists or not and then write `if ... else ...` but can I do this more elegantly?
And should I store `id`?

**Comment by wwwjfy** [comment]
I think you can either check if it exists before create or catch the exception and return to caller. That's the reason why unique constraint exists.

This is not relevant to the library itself, so I'm going to close it. Feel free to have further discussion in the thread.

**Comment by wwwjfy** [comment]
@telegram-coin-bot Feel free to submit feature request or even better pull request. :)
It should not be difficult to implement in the application itself.
