### ISSUE TITLE
Rename CRUDModel attributes

### ISSUE THREAD

**Issue by kigawas** [python-gino/gino#722]
`UpdateRequest.update` collides with `CRUDModel.update`

Thus, we cannot redefine the update method at the bottom model level.

I recommend adding an underline to `CRUDModel.create` like `create_`, as well as `update`, `query`, etc.

**Comment by fantix** [comment]
Could you please provide an example to describe your use case? Are you trying to overwrite the `Model.update()` method?

**Comment by kigawas** [comment]
I'd like to overwrite the default update method sometimes - especially for some base classes.

**Comment by kigawas** [comment]
I misunderstood. 

After closer inspection, I realized just need to overwrite `_update`, `_delete` etc.
