### ISSUE TITLE
Set `command_timeout` for all queries

### ISSUE THREAD

**Issue by thomas-maschler** [python-gino/gino#725]
* GINO version: 1.0.1
* Python version: 3.8
* asyncpg version: 0.21.0
* aiocontextvars version:
* PostgreSQL version: 11.6

### Description

I'd like to set a maximum execution time for queries and cancel all queries server-side if limit is exceeded. Similar to the `SET statement_timeout = 10000;` in PostgreSQL.

Asyncpg has the connection parameter `command_timeout`, which seems to to the same thing. How can I make use of it in Gino with FastAPI?

### What I Did

```python

app = FastAPI(title="My App")

db = Gino(
    app,
    host=DATABASE_CONFIG.host,
    port=DATABASE_CONFIG.port,
    user=DATABASE_CONFIG.username,
    password=DATABASE_CONFIG.password,
    database=DATABASE_CONFIG.database,
    pool_min_size=5,
    pool_max_size=10,
    command_timeout=10000
)
```
This doesn't work.

How else can I set this option?

**Comment by fantix** [comment]
I think this is a [gino-starlette](https://github.com/python-gino/gino-starlette) question:

https://github.com/python-gino/gino-starlette/blob/69115d78661962e7544c368f41975d79ba168d71/src/gino_starlette.py#L122-L123

> ``kwargs`` - other parameters passed to the specified dialects, like ``asyncpg``. Unrecognized parameters will cause exceptions.

So I think this will work:

```python
from gino.ext.starlette import Gino

db = Gino(
    app,
    ...,
    kwargs=dict(command_timeout=10000),
)
```

**Comment by thomas-maschler** [comment]
Ahh, thanks for clarifying. I somehow read `kwargs` as `**kwargs`. This makes more sense now.
