### ISSUE TITLE
demo 运输

### ISSUE THREAD

**Issue by VarWolf** [python-gino/gino#739]
* GINO version:
* Python version:
* asyncpg version:
* aiocontextvars version:
![image](https://user-images.githubusercontent.com/46372869/100611473-59ad6900-334c-11eb-8e25-8a3961dfd25d.png)

* PostgreSQL version:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
![image](https://user-images.githubusercontent.com/46372869/100611496-616d0d80-334c-11eb-87a8-c9d7cb941868.png)

**Comment by Chaostheorie** [comment]
Most likely related to [this issue](https://github.com/python-gino/gino-starlette/issues/20) for gino-starlette

**Comment by wwwjfy** [comment]
Closing it because too little information is provided. It looks like the extension is not used, but Gino itself directly.
Feel free to reopen.
