### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by Scruha** [python-gino/gino#820]
**Describe the bug**
Dependencies issue between FastAPI and gino[gino-starlette]

**To Reproduce**
poetry add FastAPI 
poetry add gino[pg,starlette]
**Expected result**
```
Successful installing
```

**Actual result**
```
Because no versions of gino match >1.0.1,<2.0.0
 and gino (1.0.1) depends on gino-starlette (>=0.1.1,<0.2.0), gino (>=1.0.1,<2.0.0) requires gino-starlette (>=0.1.1,<0.2.0).
Thus, gino (>=1.0.1,<2.0.0) requires starlette (>=0.13.0,<0.15.0 || >=0.16,<0.18 || >=0.19,<0.20).
And because fastapi (0.89.1) depends on starlette (0.22.0)
 and no versions of fastapi match >0.89.1,<0.90.0, gino (>=1.0.1,<2.0.0) is incompatible with fastapi (>=0.89.1,<0.90.0).
So, because auth service based on jwt tecnology depends on both fastapi (^0.89.1) and gino (^1.0.1), version solving failed.
```

**Environment (please complete the following information):**
 - GINO: [e.g. 1.0.1]
 - python = "^3.11"
 - fastapi = "^0.89.1"

**Comment by Pentusha** [comment]
Please take a look on this issue and related PR https://github.com/python-gino/gino-starlette/issues/37

**Comment by Scruha** [comment]
Sounds like yes
